import type { AbsHelper } from './helpers/abs';
import type { AcosHelper } from './helpers/acos';
import type { AcoshHelper } from './helpers/acosh';
import type { AddHelper } from './helpers/add';
import type { AsinHelper } from './helpers/asin';
import type { AsinhHelper } from './helpers/asinh';
import type { AtanHelper } from './helpers/atan';
import type { Atan2Helper } from './helpers/atan2';
import type { AtanhHelper } from './helpers/atanh';
import type { CbrtHelper } from './helpers/cbrt';
import type { CeilHelper } from './helpers/ceil';
import type { Clz32Helper } from './helpers/clz32';
import type { CosHelper } from './helpers/cos';
import type { CoshHelper } from './helpers/cosh';
import type { DivHelper } from './helpers/div';
import type { ExpHelper } from './helpers/exp';
import type { Expm1Helper } from './helpers/expm1';
import type { FloorHelper } from './helpers/floor';
import type { FroundHelper } from './helpers/fround';
import type { GcdHelper } from './helpers/gcd';
import type { HypotHelper } from './helpers/hypot';
import type { ImulHelper } from './helpers/imul';
import type { LcmHelper } from './helpers/lcm';
import type { LogEHelper } from './helpers/log-e';
import type { Log10Helper } from './helpers/log10';
import type { Log1PHelper } from './helpers/log1p';
import type { Log2Helper } from './helpers/log2';
import type { MaxHelper } from './helpers/max';
import type { MinHelper } from './helpers/min';
import type { ModHelper } from './helpers/mod';
import type { MultHelper } from './helpers/mult';
import type { PowHelper } from './helpers/pow';
import type { RandomHelper } from './helpers/random';
import type { RoundHelper } from './helpers/round';
import type { SignHelper } from './helpers/sign';
import type { SinHelper } from './helpers/sin';
import type { SqrtHelper } from './helpers/sqrt';
import type { SubHelper } from './helpers/sub';
import type { SumHelper } from './helpers/sum';
import type { TanHelper } from './helpers/tan';
import type { TanhHelper } from './helpers/tanh';
import type { TruncHelper } from './helpers/trunc';

export default class EmberMathHelpersRegistry {
  abs: AbsHelper;
  acos: AcosHelper;
  acosh: AcoshHelper;
  add: AddHelper;
  asin: AsinHelper;
  asinh: AsinhHelper;
  atan: AtanHelper;
  atan2: Atan2Helper;
  atanh: AtanhHelper;
  cbrt: CbrtHelper;
  ceil: CeilHelper;
  clz32: Clz32Helper;
  cos: CosHelper;
  cosh: CoshHelper;
  div: DivHelper;
  exp: ExpHelper;
  expm1: Expm1Helper;
  floor: FloorHelper;
  fround: FroundHelper;
  gcd: GcdHelper;
  hypot: HypotHelper;
  imul: ImulHelper;
  lcm: LcmHelper;
  'log-e': LogEHelper;
  log10: Log10Helper;
  log1p: Log1PHelper;
  log2: Log2Helper;
  max: MaxHelper;
  min: MinHelper;
  mod: ModHelper;
  mult: MultHelper;
  pow: PowHelper;
  random: RandomHelper;
  round: RoundHelper;
  sign: SignHelper;
  sin: SinHelper;
  sqrt: SqrtHelper;
  sub: SubHelper;
  sum: SumHelper;
  tan: TanHelper;
  tanh: TanhHelper;
  trunc: TruncHelper;
}
